import { getDeviceId, loadSyncConfig, saveSyncConfig, generateSyncId, pushEncryptedSnapshot, pullEncryptedSnapshot } from './sync.js';

const DB_NAME='physics-os-db', DB_VERSION=4;
let db, documents=[], cards=[], tasks=[];
let taskFilter='open', currentProblem=null, hintIndex=0, selectedDocId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const modules=['Experimentalphysik I','Rechenmethoden','Mathematik','Programmieren','Sonstiges'];
const titles={home:'Dashboard',study:'Studium',files:'Dateien',formulas:'Formeln',trainer:'Physiktrainer',mental:'Kopfrechnen',lab:'Labor',sim:'Simulationen',cards:'Lernkarten',sync:'Sync',vault:'Vault'};

const formulas=[
  {name:'Geschwindigkeit',formula:'v = Δs / Δt',topic:'Mechanik',meaning:'Ortsänderung pro Zeit.',vars:'v Geschwindigkeit · s Weg · t Zeit',units:'m/s',hint:'Bei gleichförmiger Bewegung konstant.'},
  {name:'Beschleunigung',formula:'a = Δv / Δt',topic:'Mechanik',meaning:'Geschwindigkeitsänderung pro Zeit.',vars:'a Beschleunigung · v Geschwindigkeit · t Zeit',units:'m/s²',hint:'Vorzeichen hängt von der gewählten Richtung ab.'},
  {name:'Gleichmäßig beschleunigter Weg',formula:'s = s₀ + v₀t + ½at²',topic:'Mechanik',meaning:'Ort bei konstanter Beschleunigung.',vars:'s Ort · v₀ Anfangsgeschwindigkeit · a Beschleunigung · t Zeit',units:'m',hint:'Nur für konstantes a.'},
  {name:'Newton II',formula:'F = m · a',topic:'Mechanik',meaning:'Kraft verursacht Beschleunigung.',vars:'F Kraft · m Masse · a Beschleunigung',units:'N = kg·m/s²',hint:'Vektoriell denken.'},
  {name:'Impuls',formula:'p = m · v',topic:'Mechanik',meaning:'Bewegungsgröße eines Körpers.',vars:'p Impuls · m Masse · v Geschwindigkeit',units:'kg·m/s',hint:'Impuls ist eine Vektorgröße.'},
  {name:'Kinetische Energie',formula:'Eₖ = ½mv²',topic:'Mechanik',meaning:'Energie der Bewegung.',vars:'Eₖ Energie · m Masse · v Geschwindigkeit',units:'J',hint:'v geht quadratisch ein.'},
  {name:'Potentielle Energie',formula:'Eₚ = mgh',topic:'Mechanik',meaning:'Lageenergie nahe der Erdoberfläche.',vars:'m Masse · g Fallbeschleunigung · h Höhe',units:'J',hint:'Nullniveau für h festlegen.'},
  {name:'Arbeit',formula:'W = ∫ F · ds',topic:'Mechanik',meaning:'Energieübertragung entlang eines Weges.',vars:'W Arbeit · F Kraft · s Weg',units:'J',hint:'Bei konstanter paralleler Kraft: W=Fs.'},
  {name:'Zentripetalkraft',formula:'F = mv²/r',topic:'Mechanik',meaning:'Radialkraft bei Kreisbewegung.',vars:'m Masse · v Geschwindigkeit · r Radius',units:'N',hint:'Zeigt zum Kreismittelpunkt.'},
  {name:'Ohmsches Gesetz',formula:'U = R · I',topic:'Elektrizität',meaning:'Zusammenhang von Spannung, Widerstand und Strom.',vars:'U Spannung · R Widerstand · I Strom',units:'V = Ω·A',hint:'Für ohmsche Bauteile.'},
  {name:'Elektrische Leistung',formula:'P = U · I',topic:'Elektrizität',meaning:'Umgesetzte elektrische Energie pro Zeit.',vars:'P Leistung · U Spannung · I Strom',units:'W',hint:'Mit U=RI auch P=I²R.'},
  {name:'Coulomb-Kraft',formula:'F = (1/4πε₀) · q₁q₂/r²',topic:'Elektrizität',meaning:'Kraft zwischen Punktladungen.',vars:'q Ladung · r Abstand · ε₀ Feldkonstante',units:'N',hint:'Vorzeichen bestimmt Anziehung/Abstoßung.'},
  {name:'Wellenbeziehung',formula:'v = λf',topic:'Wellen',meaning:'Geschwindigkeit, Wellenlänge und Frequenz.',vars:'v Geschwindigkeit · λ Wellenlänge · f Frequenz',units:'m/s',hint:'Im Medium ist v materialabhängig.'},
  {name:'Photonenenergie',formula:'E = hf',topic:'Quantenphysik',meaning:'Energie eines Photons.',vars:'E Energie · h Planck-Konstante · f Frequenz',units:'J',hint:'Auch E=hc/λ.'},
  {name:'de-Broglie-Wellenlänge',formula:'λ = h/p',topic:'Quantenphysik',meaning:'Materiewellenlänge eines Teilchens.',vars:'λ Wellenlänge · h Planck-Konstante · p Impuls',units:'m',hint:'Je größer p, desto kleiner λ.'},
  {name:'Ideale Gasgleichung',formula:'pV = nRT',topic:'Thermodynamik',meaning:'Zustandsgleichung eines idealen Gases.',vars:'p Druck · V Volumen · n Stoffmenge · T Temperatur',units:'Pa·m³',hint:'T immer in Kelvin.'},
  {name:'Stefan–Boltzmann',formula:'P = σAT⁴',topic:'Astrophysik',meaning:'Strahlungsleistung eines schwarzen Körpers.',vars:'P Leistung · A Fläche · T Temperatur',units:'W',hint:'T in Kelvin.'},
  {name:'Wiensches Verschiebungsgesetz',formula:'λmax = b/T',topic:'Astrophysik',meaning:'Wellenlänge des Strahlungsmaximums.',vars:'λmax Maximum · b Wien-Konstante · T Temperatur',units:'m',hint:'Heißer → Maximum bei kürzerer Wellenlänge.'},
  {name:'Gravitationskraft',formula:'F = Gm₁m₂/r²',topic:'Astrophysik',meaning:'Gravitation zweier Massen.',vars:'G Gravitationskonstante · m Massen · r Abstand',units:'N',hint:'Immer anziehend.'},
  {name:'Fluchtgeschwindigkeit',formula:'vₑ = √(2GM/r)',topic:'Astrophysik',meaning:'Minimale Geschwindigkeit zum Entkommen.',vars:'G Konstante · M Masse · r Radius',units:'m/s',hint:'Ohne Atmosphäre und Rotation.'},
  {name:'Lorentzfaktor',formula:'γ = 1/√(1-v²/c²)',topic:'Relativität',meaning:'Relativistischer Faktor.',vars:'v Geschwindigkeit · c Lichtgeschwindigkeit',units:'dimensionslos',hint:'Für v≪c ist γ≈1.'}
];
const conceptLexicon=[['Mechanik',['kraft','beschleunigung','geschwindigkeit','impuls','energie','bewegung']],['Elektrizität',['spannung','strom','widerstand','ladung','coulomb']],['Wellen',['welle','frequenz','wellenlänge']],['Quantenphysik',['photon','planck','quant','de broglie']],['Astrophysik',['stern','schwarzkörper','gravitation','orbit','planet']],['Thermodynamik',['temperatur','gas','druck','wärme']]];

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('documents'))d.createObjectStore('documents',{keyPath:'id',autoIncrement:true});if(!d.objectStoreNames.contains('cards'))d.createObjectStore('cards',{keyPath:'id',autoIncrement:true});if(!d.objectStoreNames.contains('tasks'))d.createObjectStore('tasks',{keyPath:'id',autoIncrement:true});};r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function getAll(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function addOne(name,v){return new Promise((res,rej)=>{const r=store(name,'readwrite').add(v);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function putOne(name,v){return new Promise((res,rej)=>{const r=store(name,'readwrite').put(v);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function deleteOne(name,id){return new Promise((res,rej)=>{const r=store(name,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clearStore(name){return new Promise((res,rej)=>{const r=store(name,'readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function refresh(){documents=(await getAll('documents')).sort((a,b)=>(b.importedAt||0)-(a.importedAt||0));cards=(await getAll('cards')).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));tasks=(await getAll('tasks')).sort((a,b)=>(a.done?1:0)-(b.done?1:0)||String(a.due||'9999').localeCompare(String(b.due||'9999')));renderAll()}

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showNotice(t){const n=$('#notice');n.textContent=t;n.classList.remove('hidden');clearTimeout(showNotice.t);showNotice.t=setTimeout(()=>n.classList.add('hidden'),3200)}
function humanSize(n=0){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}
function num(v){return Number(String(v).replace(',','.'))}
function fmt(v,d=3){return Number.isFinite(v)?Number(v.toFixed(d)).toLocaleString('de-DE'):'—'}
function localDate(){return new Date().toISOString().slice(0,10)}

function go(tab){$$('.tab').forEach(x=>x.classList.remove('active'));$(`#tab-${tab}`)?.classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#pageTitle').textContent=titles[tab]||tab;if(tab==='lab')renderLab();if(tab==='sim'){requestAnimationFrame(()=>{drawProjectile();drawBlackbody()})}if(tab==='mental')mentalFocus()}
$$('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));

$$('.info-btn').forEach(b=>b.onclick=e=>{e.stopPropagation();const p=$('#infoPopover'),r=b.getBoundingClientRect();$('#infoText').textContent=b.dataset.info||'';p.classList.remove('hidden');const w=Math.min(330,innerWidth-24);p.style.width=`${w}px`;p.style.left=`${Math.max(12,Math.min(innerWidth-w-12,r.left-w+25))}px`;p.style.top=`${Math.min(innerHeight-140,r.bottom+8)}px`});
$('#closeInfo').onclick=()=>$('#infoPopover').classList.add('hidden');document.addEventListener('click',e=>{if(!e.target.closest('.info-btn')&&!e.target.closest('#infoPopover'))$('#infoPopover').classList.add('hidden')});

const commands=[['Kopfrechnen','mental'],['Physiktrainer','trainer'],['Formeln','formulas'],['Messdaten-Labor','lab'],['Simulationen','sim'],['Dateien','files'],['Lernkarten','cards'],['Studium','study']];
function openCommands(){const m=$('#commandPalette');m.classList.remove('hidden');$('#commandSearch').value='';renderCommands('');setTimeout(()=>$('#commandSearch').focus(),40)}
function renderCommands(q){q=q.toLowerCase();$('#commandList').innerHTML=commands.filter(([n])=>n.toLowerCase().includes(q)).map(([n,t])=>`<button class="command-item" data-cmd="${t}"><span>${n}</span><span>↵</span></button>`).join('');$$('[data-cmd]').forEach(b=>b.onclick=()=>{$('#commandPalette').classList.add('hidden');go(b.dataset.cmd)})}
$('#commandButton').onclick=openCommands;$('#commandSearch').oninput=e=>renderCommands(e.target.value);$('#commandPalette').onclick=e=>{if(e.target===$('#commandPalette'))$('#commandPalette').classList.add('hidden')};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands()}if(e.key==='Escape')$$('.modal').forEach(m=>m.classList.add('hidden'))});

$('#taskModule').innerHTML=modules.map(x=>`<option>${x}</option>`).join('');
$('#saveTask').onclick=async()=>{const title=$('#taskTitle').value.trim();if(!title)return showNotice('Titel fehlt.');await addOne('tasks',{title,module:$('#taskModule').value,due:$('#taskDue').value,priority:$('#taskPriority').value,effort:$('#taskEffort').value,done:false,createdAt:Date.now()});$('#taskTitle').value='';await refresh();showNotice('Aufgabe gespeichert.')};
$$('[data-task-filter]').forEach(b=>b.onclick=()=>{taskFilter=b.dataset.taskFilter;$$('[data-task-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});
function renderTasks(){const list=tasks.filter(t=>taskFilter==='all'||(taskFilter==='done'?t.done:!t.done));$('#taskList').innerHTML=list.length?list.map(t=>`<div class="task-row ${t.done?'done':''}"><button class="icon-btn task-toggle" data-id="${t.id}">${t.done?'✓':'○'}</button><div class="task-main"><b>${esc(t.title)}</b><small>${esc(t.module||'Sonstiges')} ${t.due?`· ${new Date(t.due+'T12:00').toLocaleDateString('de-DE')}`:''} · ${esc(t.effort||'')}</small></div><span class="tag">${esc(t.priority||'mittel')}</span><button class="icon-btn task-delete" data-id="${t.id}">×</button></div>`).join(''):'<div class="empty">Keine Aufgaben.</div>';$$('.task-toggle').forEach(b=>b.onclick=async()=>{const t=tasks.find(x=>x.id===Number(b.dataset.id));t.done=!t.done;t.doneAt=t.done?Date.now():null;await putOne('tasks',t);await refresh()});$$('.task-delete').forEach(b=>b.onclick=async()=>{await deleteOne('tasks',Number(b.dataset.id));await refresh()})}
function renderModules(){const html=modules.map(m=>{const all=tasks.filter(t=>t.module===m),done=all.filter(t=>t.done).length,p=all.length?Math.round(done/all.length*100):0;return `<div class="module-row"><span>${m}</span><div class="bar"><i style="width:${p}%"></i></div><small>${p}%</small></div>`}).join('');$('#moduleList').innerHTML=html;const total=tasks.length,done=tasks.filter(t=>t.done).length;$('#moduleProgressText').textContent=`${total?Math.round(done/total*100):0} %`}
function nextTask(){const open=tasks.filter(t=>!t.done);if(!open.length)return null;const rank={hoch:0,mittel:1,niedrig:2};return open.sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||(rank[a.priority]??1)-(rank[b.priority]??1))[0]}

function classify(file,text=''){const h=`${file.name} ${text.slice(0,2500)}`.toLowerCase();if(/goodnotes|mitschrift/.test(h))return'Goodnotes';if(/praktikum|versuch|messwert|labor|protokoll/.test(h))return'Praktikum';if(/übung|uebung|blatt|aufgabe/.test(h))return'Übung';if(/vorlesung|skript|lecture|folien/.test(h))return'Vorlesung';if(/\.csv$|\.tsv$/.test(h))return'Daten';return'Sonstiges'}
function detectConcepts(text=''){const h=text.toLowerCase();return conceptLexicon.map(([name,terms])=>({name,score:terms.reduce((s,t)=>s+(h.match(new RegExp(t,'g'))?.length||0),0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,6)}
function analyzeText(text='',name=''){const c=detectConcepts(`${name} ${text}`),words=text.trim()?text.trim().split(/\s+/).length:0,numbers=(text.match(/[-+]?\d+(?:[.,]\d+)?/g)||[]).length,equations=(text.match(/[A-Za-zα-ωΑ-Ω][^\n]{0,16}=[^\n]{1,34}/g)||[]).slice(0,5);return{concepts:c,words,numbers,equations}}
async function extractText(file){const ext=file.name.split('.').pop()?.toLowerCase();return file.type.startsWith('text/')||['txt','md','csv','tsv'].includes(ext)?await file.text():''}
async function importFiles(files){if(!files.length)return;for(const file of files){const text=await extractText(file),analysis=analyzeText(text,file.name);await addOne('documents',{name:file.name,mime:file.type||'application/octet-stream',size:file.size,kind:classify(file,text),importedAt:Date.now(),text:text.slice(0,2000000),analysis,blob:file})}await refresh();showNotice(`${files.length} Datei(en) importiert.`)}
const drop=$('#dropzone'),fileInput=$('#fileInput');$('#chooseFiles').onclick=e=>{e.stopPropagation();fileInput.click()};drop.onclick=e=>{if(!e.target.closest('button'))fileInput.click()};fileInput.onchange=()=>importFiles([...fileInput.files]);drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');importFiles([...e.dataTransfer.files])};$('#fileSearch').oninput=renderFiles;
function openDocument(d){if(!d?.blob)return;const u=URL.createObjectURL(d.blob),a=document.createElement('a');a.href=u;a.target='_blank';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000)}
function renderFiles(){const q=($('#fileSearch')?.value||'').toLowerCase();const arr=documents.filter(d=>`${d.name} ${d.kind} ${(d.analysis?.concepts||[]).map(x=>x.name).join(' ')}`.toLowerCase().includes(q));$('#fileCount').textContent=documents.length;$('#fileTable').innerHTML=arr.length?arr.map(d=>`<div class="file-row ${selectedDocId===d.id?'selected':''}"><div class="file-main"><b>${esc(d.name)}</b><small>${esc(d.kind)} · ${humanSize(d.size)}</small></div><button class="quiet-btn analyze-doc" data-id="${d.id}">Analyse</button><button class="icon-btn open-doc" data-id="${d.id}">↗</button><button class="icon-btn delete-doc" data-id="${d.id}">×</button></div>`).join(''):'<div class="empty">Keine Dateien.</div>';$$('.analyze-doc').forEach(b=>b.onclick=()=>{selectedDocId=Number(b.dataset.id);renderFileAnalysis();renderFiles()});$$('.open-doc').forEach(b=>b.onclick=()=>openDocument(documents.find(d=>d.id===Number(b.dataset.id))));$$('.delete-doc').forEach(b=>b.onclick=async()=>{await deleteOne('documents',Number(b.dataset.id));if(selectedDocId===Number(b.dataset.id))selectedDocId=null;await refresh()})}
function renderFileAnalysis(){const d=documents.find(x=>x.id===selectedDocId);if(!d)return $('#fileAnalysis').innerHTML='<div class="empty">Wähle eine Datei.</div>';const a=d.analysis||analyzeText(d.text||'',d.name),concepts=a.concepts||[];$('#fileAnalysis').innerHTML=`<div class="analysis-card"><b>${esc(d.name)}</b><div class="mini-stats"><div><strong>${a.words||0}</strong><span>Wörter</span></div><div><strong>${a.numbers||0}</strong><span>Zahlen</span></div></div><h4>Themen</h4><div>${concepts.length?concepts.map(c=>`<span class="tag">${esc(c.name)}</span>`).join(' '):'<span class="subtle">Noch keine erkennbar.</span>'}</div>${a.equations?.length?`<h4>Mögliche Gleichungen</h4>${a.equations.map(e=>`<div class="formula">${esc(e)}</div>`).join('')}`:''}</div>`}

function renderFormulaTopics(){const topics=[...new Set(formulas.map(f=>f.topic))].sort();$('#formulaTopic').innerHTML='<option value="">Alle Themen</option>'+topics.map(t=>`<option>${t}</option>`).join('')}
function renderFormulas(){const q=$('#formulaSearch').value.toLowerCase(),topic=$('#formulaTopic').value;const arr=formulas.filter(f=>(!topic||f.topic===topic)&&`${f.name} ${f.formula} ${f.meaning} ${f.vars}`.toLowerCase().includes(q));$('#formulaGrid').innerHTML=arr.map(f=>`<article class="panel formula-card" data-formula="${formulas.indexOf(f)}"><span class="tag">${f.topic}</span><h3>${f.name}</h3><div class="formula">${f.formula}</div><p>${f.meaning}</p></article>`).join('');$$('[data-formula]').forEach(c=>c.onclick=()=>openFormula(Number(c.dataset.formula)))}
function openFormula(i){const f=formulas[i];$('#formulaDetail').innerHTML=`<span class="tag">${f.topic}</span><h2>${f.name}</h2><div class="formula" style="font-size:34px;margin:18px 0">${f.formula}</div><div class="stack"><div><b>Bedeutung</b><p class="subtle">${f.meaning}</p></div><div><b>Größen</b><p class="subtle">${f.vars}</p></div><div><b>Einheit</b><p class="subtle">${f.units}</p></div><div><b>Hinweis</b><p class="subtle">${f.hint}</p></div></div>`;$('#formulaModal').classList.remove('hidden')}
$('#formulaSearch').oninput=renderFormulas;$('#formulaTopic').onchange=renderFormulas;$$('[data-close-modal]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));$('#formulaModal').onclick=e=>{if(e.target===$('#formulaModal'))$('#formulaModal').classList.add('hidden')};

const problemGenerators={
  kinematics(){const v=ri(6,28),t=ri(3,16);return{title:'Gleichförmige Bewegung',text:`Ein Körper bewegt sich ${t} s lang mit ${v} m/s. Welche Strecke legt er zurück?`,answer:v*t,unit:'m',hints:['Gesucht ist der Weg s.','Nutze s = v · t.','Setze Geschwindigkeit und Zeit direkt ein.'],solution:`s = ${v} · ${t} = ${v*t} m`}},
  newton(){const m=ri(2,18),a=ri(2,12);return{title:'Newton II',text:`Auf eine Masse von ${m} kg wirkt eine Beschleunigung von ${a} m/s². Wie groß ist die resultierende Kraft?`,answer:m*a,unit:'N',hints:['Gesucht ist F.','Newton II: F = m · a.','Multipliziere Masse und Beschleunigung.'],solution:`F = ${m} · ${a} = ${m*a} N`}},
  energy(){const m=ri(1,12),v=ri(3,15),ans=.5*m*v*v;return{title:'Kinetische Energie',text:`Ein Körper mit ${m} kg bewegt sich mit ${v} m/s. Wie groß ist seine kinetische Energie?`,answer:ans,unit:'J',hints:['Gesucht ist Eₖ.','Eₖ = ½mv².','Zuerst v quadrieren.'],solution:`Eₖ = ½ · ${m} · ${v}² = ${fmt(ans,2)} J`}},
  electric(){const r=ri(2,20)*5,i=ri(2,16)/10,ans=r*i;return{title:'Ohmsches Gesetz',text:`Durch einen Widerstand von ${r} Ω fließt ein Strom von ${fmt(i,1)} A. Welche Spannung liegt an?`,answer:ans,unit:'V',hints:['Gesucht ist U.','Ohmsches Gesetz: U = R · I.','Multipliziere Widerstand und Stromstärke.'],solution:`U = ${r} · ${fmt(i,1)} = ${fmt(ans,2)} V`}}
};
function ri(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function newProblem(){const g=problemGenerators[$('#trainerTopic').value]||problemGenerators.kinematics;currentProblem=g();hintIndex=0;$('#problemCard').innerHTML=`<span class="tag">${currentProblem.title}</span><div class="problem-text">${currentProblem.text}</div>`;$('#problemUnit').textContent=currentProblem.unit;$('#problemAnswer').value='';$('#hintBox').classList.add('hidden');$('#solutionBox').classList.add('hidden');$('#hintBox').innerHTML='';$('#solutionBox').innerHTML=''}
$('#newProblem').onclick=newProblem;$('#trainerTopic').onchange=newProblem;$('#checkProblem').onclick=()=>{if(!currentProblem)return;const a=num($('#problemAnswer').value);if(!Number.isFinite(a))return showNotice('Gib einen Zahlenwert ein.');const tol=Math.max(.01,Math.abs(currentProblem.answer)*.015);if(Math.abs(a-currentProblem.answer)<=tol){showNotice('Richtig.');$('#solutionBox').innerHTML=`✓ ${currentProblem.solution}`;$('#solutionBox').classList.remove('hidden')}else showNotice('Noch nicht. Du kannst einen Tipp öffnen.')};$('#problemHint').onclick=()=>{if(!currentProblem)return;const hints=currentProblem.hints;$('#hintBox').textContent=hints[Math.min(hintIndex,hints.length-1)];$('#hintBox').classList.remove('hidden');hintIndex++};$('#showProblemSolution').onclick=()=>{if(!currentProblem)return;$('#solutionBox').innerHTML=currentProblem.solution;$('#solutionBox').classList.remove('hidden')};

const MENTAL_KEY='physics-os-mental-v1';
let mental={op:'mix',level:'medium',current:null,lastKeys:[],missed:[],stats:{date:localDate(),attempted:0,correct:0,solved:0}};
function loadMental(){try{const x=JSON.parse(localStorage.getItem(MENTAL_KEY)||'{}');mental={...mental,...x,stats:{...mental.stats,...(x.stats||{})}}}catch{}if(mental.stats.date!==localDate())mental.stats={date:localDate(),attempted:0,correct:0,solved:0}}
function saveMental(){localStorage.setItem(MENTAL_KEY,JSON.stringify(mental));renderMentalStats()}
const levelNotes={easy:'Kleine Zahlen, Grundrechenarten und glatte Divisionen.',medium:'Zweistellige Zahlen, größeres Einmaleins und etwas mehr Zerlegen.',hard:'Größere Zahlen und Aufgaben, bei denen Rechentricks besonders helfen.'};
function mentalRanges(level){return level==='easy'?{add:[2,30],sub:[2,40],mul:[2,10],div:[2,10]}:level==='medium'?{add:[15,180],sub:[15,220],mul:[3,18],div:[3,18]}:{add:[80,950],sub:[80,1200],mul:[7,35],div:[7,35]}}
function makeMentalProblem(forceOp=null){const ops=['add','sub','mul','div'],op=forceOp||(mental.op==='mix'?ops[ri(0,3)]:mental.op),r=mentalRanges(mental.level);let a,b,answer,symbol,key;for(let guard=0;guard<80;guard++){if(op==='add'){a=ri(...r.add);b=ri(...r.add);answer=a+b;symbol='+'}if(op==='sub'){a=ri(...r.sub);b=ri(...r.sub);if(b>a)[a,b]=[b,a];answer=a-b;symbol='−'}if(op==='mul'){a=ri(...r.mul);b=ri(...r.mul);answer=a*b;symbol='×'}if(op==='div'){b=ri(...r.div);answer=ri(2,mental.level==='hard'?28:16);a=b*answer;symbol='÷'}key=`${a}${op}${b}`;if(!mental.lastKeys.includes(key))break}return{a,b,answer,op,symbol,key}}
function trickFor(p){if(!p)return'';const{a,b,op}=p;if(op==='add'){const near=[10,20,50,100,200,500,1000].find(n=>Math.abs(a-n)<=3)||[10,20,50,100,200,500,1000].find(n=>Math.abs(b-n)<=3);if(near){const x=Math.abs(a-near)<=3?a:b,y=x===a?b:a,d=near-x;return`<b>Ausgleichen</b>Runde ${x} auf ${near}. Rechne ${near} + ${y}${d?` und gleiche danach ${d>0?`− ${d}`:`+ ${Math.abs(d)}`}`:''}.`}return`<b>Zerlegen</b>Rechne erst die Zehner/Hunderter und danach den Rest. Zum Beispiel ${a} + ${b}: zerlege ${b} in eine runde Zahl und den Rest.`}if(op==='sub'){if(b%10>=7)return`<b>Ergänzen statt abziehen</b>Du kannst von ${b} bis ${a} hochzählen: erst zur nächsten runden Zahl, dann weiter.`;return`<b>In Schritten</b>Zerlege ${b}. Ziehe zuerst Zehner/Hunderter ab, danach die Einer.`}if(op==='mul'){if(b===9||a===9){const x=b===9?a:b;return`<b>× 9</b>${x} × 9 = ${x} × 10 − ${x}.`}if(b===11||a===11){const x=b===11?a:b;return`<b>× 11</b>Rechne ${x} × 10 + ${x}.`}if(a%2===0||b%2===0)return`<b>Verdoppeln & halbieren</b>Bei einem geraden Faktor kannst du einen Faktor halbieren und den anderen verdoppeln. Das Produkt bleibt gleich.`;return`<b>Distributivgesetz</b>Zerlege einen Faktor in eine nahe runde Zahl. Beispiel: ${a} × ${b} = ${a} × (${Math.floor(b/10)*10||10} + Rest).`}if(op==='div'){if(a%10===0)return`<b>Rückwärts multiplizieren</b>Frage dich: ${b} × welche Zahl ergibt ${a}?`;return`<b>In passende Pakete zerlegen</b>Suche Vielfache von ${b}, die zusammen ${a} ergeben. Oder denke die Division als fehlenden Faktor: ${b} × ? = ${a}.`}return''}
function nextMental(){let p;if(mental.missed.length>=2&&Math.random()<.22)p=mental.missed.shift();else p=makeMentalProblem();mental.current=p;mental.lastKeys=[p.key,...mental.lastKeys.filter(k=>k!==p.key)].slice(0,12);$('#mentalExpression').textContent=`${p.a} ${p.symbol} ${p.b}`;$('#mentalAnswer').value='';$('#mentalFeedback').textContent='';$('#mentalFeedback').className='mental-feedback';$('#mentalTip').classList.add('hidden');$('#mentalTip').innerHTML='';mentalFocus();saveMental()}
function mentalFocus(){setTimeout(()=>$('#mentalAnswer')?.focus(),40)}
function checkMental(){const p=mental.current;if(!p)return;const a=num($('#mentalAnswer').value);if(!Number.isFinite(a))return;mental.stats.attempted++;mental.stats.solved++;if(a===p.answer){mental.stats.correct++;$('#mentalFeedback').textContent='Richtig ✓';$('#mentalFeedback').className='mental-feedback good'}else{$('#mentalFeedback').textContent=`Noch nicht — ${a} stimmt nicht.`;$('#mentalFeedback').className='mental-feedback bad';if(!mental.missed.some(x=>x.key===p.key))mental.missed.push(p)}saveMental()}
function revealMental(){const p=mental.current;if(!p)return;$('#mentalFeedback').textContent=`${p.answer}`;$('#mentalFeedback').className='mental-feedback';if(!mental.missed.some(x=>x.key===p.key))mental.missed.push(p);saveMental()}
function renderMentalStats(){const s=mental.stats;$('#mentalToday').textContent=s.solved||0;$('#statMental').textContent=s.solved||0;$('#mentalAccuracy').textContent=s.attempted?`${Math.round(s.correct/s.attempted*100)} %`:'—';$('#mentalLevelNote').innerHTML=`<div class="mental-level-copy">${levelNotes[mental.level]}</div>`;$$('#mentalOps button').forEach(b=>b.classList.toggle('active',b.dataset.op===mental.op));$('#mentalLevel').value=mental.level}
$$('#mentalOps button').forEach(b=>b.onclick=()=>{mental.op=b.dataset.op;saveMental();nextMental()});$('#mentalLevel').onchange=e=>{mental.level=e.target.value;saveMental();nextMental()};$('#mentalCheck').onclick=checkMental;$('#mentalNext').onclick=nextMental;$('#mentalTipBtn').onclick=()=>{const t=$('#mentalTip');t.innerHTML=trickFor(mental.current);t.classList.toggle('hidden')};$('#mentalRevealBtn').onclick=revealMental;$('#mentalAnswer').addEventListener('keydown',e=>{if(e.key==='Enter')checkMental()});

function parseDelimited(text,delimiter){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return null;delimiter=delimiter||(lines[0].includes('\t')?'\t':lines[0].includes(';')?';':',');const rows=lines.map(l=>l.split(delimiter).map(v=>v.trim().replace(/^"|"$/g,'')));const conv=v=>Number(String(v).replace(',','.'));const firstNumeric=rows[0].every(v=>Number.isFinite(conv(v)));const headers=firstNumeric?rows[0].map((_,i)=>`Spalte ${i+1}`):rows[0];const data=firstNumeric?rows:rows.slice(1);const columns=headers.map((_,i)=>data.map(r=>conv(r[i])).filter(Number.isFinite));return{headers,columns}}
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN;function sd(a){if(a.length<2)return NaN;const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1))}
function regression(x,y){const n=Math.min(x.length,y.length);if(n<2)return null;x=x.slice(0,n);y=y.slice(0,n);const mx=mean(x),my=mean(y),sxx=x.reduce((s,v)=>s+(v-mx)**2,0);if(!sxx)return null;const slope=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0)/sxx,intercept=my-slope*mx,p=x.map(v=>slope*v+intercept),ssr=y.reduce((s,v,i)=>s+(v-p[i])**2,0),sst=y.reduce((s,v)=>s+(v-my)**2,0),r2=sst?1-ssr/sst:1,se=n>2?Math.sqrt(ssr/(n-2)):0;return{slope,intercept,r2,slopeSE:se/Math.sqrt(sxx),interceptSE:se*Math.sqrt(1/n+mx*mx/sxx)}}
function renderLab(){const data=documents.filter(d=>/\.(csv|tsv)$/i.test(d.name));$('#labSelect').innerHTML=data.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('');$('#labSelect').classList.toggle('hidden',!data.length);$('#labEmpty').classList.toggle('hidden',!!data.length);if(!data.length){$('#labResults').innerHTML='';return}const id=Number($('#labSelect').value)||data[0].id,d=data.find(x=>x.id===id)||data[0];$('#labSelect').value=d.id;const t=parseDelimited(d.text||'',d.name.toLowerCase().endsWith('.tsv')?'\t':null);if(!t)return;const sums=t.headers.map((h,i)=>({h,n:t.columns[i].length,m:mean(t.columns[i]),s:sd(t.columns[i])}));const fit=t.columns.length>=2?regression(t.columns[0],t.columns[1]):null;$('#labResults').innerHTML=`<div class="lab-summary">${sums.slice(0,4).map(s=>`<div class="panel"><strong>${fmt(s.m,4)}</strong><small>${esc(s.h)} · n=${s.n} · σ=${fmt(s.s,3)}</small></div>`).join('')}</div>${fit?`<article class="panel fit-card"><span class="tag">lineare Regression</span><div class="fit-equation">y = ${fmt(fit.slope,5)}x ${fit.intercept>=0?'+':'−'} ${fmt(Math.abs(fit.intercept),5)}</div><span class="subtle">R² = ${fit.r2.toFixed(5)} · m = ${fmt(fit.slope,5)} ± ${fmt(fit.slopeSE,3)}</span></article><article class="panel plot-wrap"><canvas id="labPlot" width="900" height="390"></canvas></article>`:''}`;if(fit)requestAnimationFrame(()=>drawScatter($('#labPlot'),t.columns[0],t.columns[1],fit))}
$('#labSelect').onchange=renderLab;
function canvasBase(c){const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#090f1b';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#202c41';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(55,(h-45)*i/5);ctx.lineTo(w-15,(h-45)*i/5);ctx.stroke()}return{ctx,w,h}}
function drawScatter(c,x,y,fit){if(!c||!x.length||!y.length)return;const{ctx,w,h}=canvasBase(c),n=Math.min(x.length,y.length),xmin=Math.min(...x),xmax=Math.max(...x),ymin=Math.min(...y),ymax=Math.max(...y),px=v=>55+(v-xmin)/(xmax-xmin||1)*(w-80),py=v=>h-35-(v-ymin)/(ymax-ymin||1)*(h-65);ctx.fillStyle='#8ea0ff';for(let i=0;i<n;i++){ctx.beginPath();ctx.arc(px(x[i]),py(y[i]),4,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#55d5c5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px(xmin),py(fit.slope*xmin+fit.intercept));ctx.lineTo(px(xmax),py(fit.slope*xmax+fit.intercept));ctx.stroke()}
$('#calcUncertainty').onclick=()=>{const x=num($('#ux').value),dx=num($('#udx').value),a=num($('#ua').value),y=num($('#uy').value),dy=num($('#udy').value),b=num($('#ub').value);if(![x,dx,a,y,dy,b].every(Number.isFinite)||x===0||y===0)return showNotice('Bitte gültige Werte eintragen.');const z=x**a*y**b,rel=Math.sqrt((a*dx/x)**2+(b*dy/y)**2),dz=Math.abs(z)*rel;$('#uncertaintyResult').innerHTML=`z = <b>${fmt(z,5)}</b> &nbsp; Δz = <b>${fmt(dz,5)}</b> &nbsp; (${fmt(rel*100,2)} %)`};

function drawProjectile(){const c=$('#projectileCanvas');if(!c)return;const v=num($('#v0Range').value),angle=num($('#angleRange').value),g=num($('#gRange').value),rad=angle*Math.PI/180,t=2*v*Math.sin(rad)/g,R=v*Math.cos(rad)*t,H=(v*Math.sin(rad))**2/(2*g);$('#v0Out').textContent=`${v} m/s`;$('#angleOut').textContent=`${angle}°`;$('#gOut').textContent=`${fmt(g,2)} m/s²`;$('#projectileBadge').textContent=`R ${fmt(R,1)} m`;$('#projectileStats').innerHTML=`<div><strong>${fmt(H,1)} m</strong><span>max. Höhe</span></div><div><strong>${fmt(t,2)} s</strong><span>Flugzeit</span></div>`;const{ctx,w,h}=canvasBase(c),px=x=>45+x/(R||1)*(w-70),py=y=>h-30-y/(H*1.18||1)*(h-55);ctx.strokeStyle='#8296ff';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<=100;i++){const ti=t*i/100,x=v*Math.cos(rad)*ti,y=v*Math.sin(rad)*ti-.5*g*ti*ti;i?ctx.lineTo(px(x),py(Math.max(0,y))):ctx.moveTo(px(x),py(0))}ctx.stroke()}
['v0Range','angleRange','gRange'].forEach(id=>$('#'+id).oninput=drawProjectile);
function planck(lambda,T){const h=6.62607015e-34,c=299792458,k=1.380649e-23;return(2*h*c*c)/(lambda**5)/(Math.exp(h*c/(lambda*k*T))-1)}
function drawBlackbody(){const c=$('#blackbodyCanvas');if(!c)return;const T=num($('#tempRange').value),peak=2.897771955e-3/T,nm=peak*1e9,sigma=5.670374419e-8,p=sigma*T**4;$('#tempOut').textContent=`${T} K`;$('#blackbodyPeak').textContent=`λmax ${Math.round(nm)} nm`;$('#blackbodyStats').innerHTML=`<div><strong>${Math.round(nm)} nm</strong><span>Wien-Maximum</span></div><div><strong>${p.toExponential(2)}</strong><span>W/m²</span></div>`;const{ctx,w,h}=canvasBase(c),xs=[],ys=[];for(let nmv=100;nmv<=2500;nmv+=12){xs.push(nmv);ys.push(planck(nmv*1e-9,T))}const max=Math.max(...ys),px=x=>45+(x-100)/2400*(w-65),py=y=>h-28-y/max*(h-50);ctx.strokeStyle='#7e91ff';ctx.lineWidth=3;ctx.beginPath();ys.forEach((y,i)=>i?ctx.lineTo(px(xs[i]),py(y)):ctx.moveTo(px(xs[i]),py(y)));ctx.stroke();ctx.strokeStyle='#55d5c5';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px(nm),15);ctx.lineTo(px(nm),h-28);ctx.stroke()}
$('#tempRange').oninput=drawBlackbody;

function cardDue(c){return!c.nextReview||c.nextReview<=Date.now()}
$('#addCard').onclick=async()=>{const front=$('#cardFront').value.trim(),back=$('#cardBack').value.trim(),topic=$('#cardTopic').value.trim()||'Allgemein';if(!front||!back)return showNotice('Vorder- und Rückseite fehlen.');await addOne('cards',{front,back,topic,createdAt:Date.now(),interval:0,nextReview:Date.now(),reviews:0});$('#cardFront').value='';$('#cardBack').value='';await refresh()};
function renderCards(){const due=cards.filter(cardDue).sort((a,b)=>(a.nextReview||0)-(b.nextReview||0));$('#cardCount').textContent=due.length;$('#statDueCards').textContent=due.length;const c=due[0];$('#reviewBox').innerHTML=c?`<div class="review-card"><span class="tag">${esc(c.topic)}</span><div class="review-front">${esc(c.front)}</div><button class="text-btn reveal-card" data-id="${c.id}">Antwort zeigen</button><div class="review-back hidden">${esc(c.back)}</div><div class="review-actions hidden"><button data-rate="again" data-id="${c.id}">Nochmal</button><button data-rate="hard" data-id="${c.id}">Schwer</button><button data-rate="good" data-id="${c.id}">Gut</button><button data-rate="easy" data-id="${c.id}">Leicht</button></div></div>`:'<div class="empty">Heute nichts fällig.</div>';$('.reveal-card')?.addEventListener('click',e=>{const box=e.target.closest('.review-card');box.querySelector('.review-back').classList.remove('hidden');box.querySelector('.review-actions').classList.remove('hidden');e.target.classList.add('hidden')});$$('[data-rate]').forEach(b=>b.onclick=()=>rateCard(Number(b.dataset.id),b.dataset.rate));$('#cardList').innerHTML=cards.length?cards.map(c=>`<div class="card-row"><div class="task-main"><b>${esc(c.front)}</b><small>${esc(c.topic)}${c.nextReview?` · ${new Date(c.nextReview).toLocaleDateString('de-DE')}`:''}</small></div><button class="icon-btn delete-card" data-id="${c.id}">×</button></div>`).join(''):'<div class="empty">Noch keine Karten.</div>';$$('.delete-card').forEach(b=>b.onclick=async()=>{await deleteOne('cards',Number(b.dataset.id));await refresh()})}
async function rateCard(id,rating){const c=cards.find(x=>x.id===id);if(!c)return;const day=86400000;let interval=c.interval||0;if(rating==='again')interval=0;if(rating==='hard')interval=Math.max(1,Math.round(interval*1.2)||1);if(rating==='good')interval=Math.max(2,Math.round(interval*2)||2);if(rating==='easy')interval=Math.max(4,Math.round(interval*2.8)||4);c.interval=interval;c.nextReview=Date.now()+(rating==='again'?10*60*1000:interval*day);c.reviews=(c.reviews||0)+1;await putOne('cards',c);await refresh()}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('#exportCards').onclick=()=>{if(!cards.length)return showNotice('Keine Karten vorhanden.');const csv=cards.map(c=>`"${c.front.replaceAll('"','""')}","${c.back.replaceAll('"','""')}"`).join('\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),'physics-os-goodnotes-cards.csv')};

function bytesToB64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}function b64ToBytes(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function deriveKey(pass,salt){const m=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function makePayload(){const docs=await Promise.all(documents.map(async d=>({name:d.name,mime:d.mime,size:d.size,kind:d.kind,importedAt:d.importedAt,text:d.text,analysis:d.analysis,data:d.blob?bytesToB64(new Uint8Array(await d.blob.arrayBuffer())):''})));return{version:4,updatedAt:new Date().toISOString(),deviceId:getDeviceId(),documents:docs,cards:cards.map(({id,...c})=>c),tasks:tasks.map(({id,...t})=>t),mental:JSON.parse(localStorage.getItem(MENTAL_KEY)||'{}')}}
async function encryptPayload(payload,pass){if(pass.length<8)throw new Error('PASS');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(pass,salt),plain=new TextEncoder().encode(JSON.stringify(payload)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain);return{protocol:1,kdf:'PBKDF2-SHA256-250000',cipher:'AES-256-GCM',salt:bytesToB64(salt),iv:bytesToB64(iv),data:bytesToB64(new Uint8Array(cipher))}}
async function decryptEnvelope(env,pass){const salt=b64ToBytes(env.salt),iv=b64ToBytes(env.iv),key=await deriveKey(pass,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,b64ToBytes(env.data));return JSON.parse(new TextDecoder().decode(plain))}
async function restorePayload(p){await clearStore('documents');await clearStore('cards');await clearStore('tasks');for(const d of p.documents||[]){const bytes=d.data?b64ToBytes(d.data):new Uint8Array(),blob=new Blob([bytes],{type:d.mime||'application/octet-stream'});await addOne('documents',{...d,blob,data:undefined})}for(const c of p.cards||[])await addOne('cards',c);for(const t of p.tasks||[])await addOne('tasks',t);if(p.mental){localStorage.setItem(MENTAL_KEY,JSON.stringify(p.mental));loadMental()}await refresh()}
$('#exportVault').onclick=async()=>{try{const env=await encryptPayload(await makePayload(),$('#vaultPass').value);downloadBlob(new Blob([JSON.stringify(env)],{type:'application/json'}),`physics-os-vault-${localDate()}.json`)}catch{showNotice('Vault-Code: mindestens 8 Zeichen.')}};$('#importVaultBtn').onclick=()=>$('#vaultInput').click();$('#vaultInput').onchange=async()=>{try{const env=JSON.parse(await $('#vaultInput').files[0].text()),p=await decryptEnvelope(env,$('#vaultPass').value);await restorePayload(p);showNotice('Backup eingelesen.')}catch{showNotice('Backup oder Vault-Code stimmt nicht.')}};
function syncConfigFromUI(){return{endpoint:$('#syncEndpoint').value.trim(),syncId:$('#syncId').value.trim(),autoSync:$('#autoSync').checked}}
function initSync(){const c=loadSyncConfig();$('#syncEndpoint').value=c.endpoint||'';$('#syncId').value=c.syncId||'';$('#autoSync').checked=!!c.autoSync;renderSyncState()}
function renderSyncState(){const c=syncConfigFromUI();$('#syncState').textContent=c.endpoint&&c.syncId?'bereit':'nicht verbunden';$('#syncPill').textContent=c.endpoint&&c.syncId?'sync bereit':'lokal'}
['syncEndpoint','syncId','autoSync'].forEach(id=>$('#'+id).addEventListener('change',()=>{saveSyncConfig(syncConfigFromUI());renderSyncState()}));$('#generateSyncId').onclick=()=>{$('#syncId').value=generateSyncId();saveSyncConfig(syncConfigFromUI());renderSyncState()};$('#copySyncId').onclick=async()=>{await navigator.clipboard?.writeText($('#syncId').value);showNotice('Sync-ID kopiert.')};
async function syncPush(){const c=syncConfigFromUI(),pass=$('#syncPass').value;if(pass.length<8)return showNotice('Vault-Code fehlt.');try{const envelope=await encryptPayload(await makePayload(),pass);await pushEncryptedSnapshot({endpoint:c.endpoint,syncId:c.syncId,envelope,deviceId:getDeviceId()});saveSyncConfig(c);showNotice('Verschlüsselt hochgeladen.')}catch{showNotice('Sync nicht möglich. Endpunkt prüfen.')}}
async function syncPull(){const c=syncConfigFromUI(),pass=$('#syncPass').value;if(pass.length<8)return showNotice('Vault-Code fehlt.');try{const remote=await pullEncryptedSnapshot({endpoint:c.endpoint,syncId:c.syncId});if(!remote)return showNotice('Noch kein Cloud-Stand.');const p=await decryptEnvelope(remote.envelope,pass);await restorePayload(p);saveSyncConfig(c);showNotice('Cloud-Stand geladen.')}catch{showNotice('Sync nicht möglich oder Vault-Code falsch.')}}
$('#syncPush').onclick=syncPush;$('#syncPull').onclick=syncPull;$('#syncNow').onclick=async()=>{const c=syncConfigFromUI();try{const remote=await pullEncryptedSnapshot({endpoint:c.endpoint,syncId:c.syncId});if(!remote)return syncPush();const pass=$('#syncPass').value,p=await decryptEnvelope(remote.envelope,pass),local=await makePayload();if(new Date(p.updatedAt||0)>new Date(local.updatedAt||0))await restorePayload(p);else await syncPush();showNotice('Synchronisiert.')}catch{showNotice('Sync nicht möglich.')}};
document.addEventListener('visibilitychange',()=>{const c=loadSyncConfig();if(document.visibilityState==='visible'&&c.autoSync&&$('#syncPass').value)$('#syncNow').click()});

function renderDashboard(){const t=nextTask();$('#statTasks').textContent=tasks.filter(x=>!x.done).length;$('#statFiles').textContent=documents.length;$('#nextFocus').innerHTML=t?`<b>${esc(t.title)}</b><small>${esc(t.module||'')} ${t.due?`· fällig ${new Date(t.due+'T12:00').toLocaleDateString('de-DE')}`:''}</small>`:'<b>Nichts offen.</b><small>Du kannst dir eine Aufgabe im Studium-Tab anlegen.</small>';$('#recentList').innerHTML=documents.length?documents.slice(0,4).map(d=>`<div><b>${esc(d.name)}</b><small>${esc(d.kind)} · ${humanSize(d.size)}</small></div>`).join(''):'<div class="empty">Noch keine Dateien.</div>'}
function renderAll(){renderDashboard();renderTasks();renderModules();renderFiles();renderFileAnalysis();renderFormulas();renderCards();renderMentalStats()}
async function init(){await openDB();loadMental();renderFormulaTopics();initSync();await refresh();newProblem();if(!mental.current)nextMental();else{$('#mentalExpression').textContent=`${mental.current.a} ${mental.current.symbol} ${mental.current.b}`;renderMentalStats()}drawProjectile();drawBlackbody();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
init().catch(err=>{console.error(err);showNotice('Physics OS konnte nicht vollständig starten.')});
