import { getDeviceId, loadSyncConfig, saveSyncConfig, generateSyncId, pushEncryptedSnapshot, pullEncryptedSnapshot } from './sync.js';
const DB_NAME='physics-os-db',DB_VERSION=1;let db;let documents=[];let cards=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const titles={home:'Dashboard',files:'Dateien & Goodnotes',formulas:'Formelbibliothek',lab:'Praktikums-Auswertung',cards:'Lernkarten',sync:'Geräte-Sync',vault:'Vault & Backup'};
const formulas=[
{name:'Newton II',formula:'F = m · a',topic:'Mechanik',meaning:'Kraft ist Masse mal Beschleunigung.',units:'N = kg · m/s²',hint:'Vektorielle Gleichung: Richtung von Kraft und Beschleunigung beachten.'},
{name:'Kinetische Energie',formula:'Eₖ = ½ m v²',topic:'Mechanik',meaning:'Bewegungsenergie eines Körpers.',units:'J = kg · m²/s²',hint:'Die Geschwindigkeit geht quadratisch ein.'},
{name:'Potentielle Energie',formula:'Eₚ = m g h',topic:'Mechanik',meaning:'Lageenergie nahe der Erdoberfläche.',units:'J',hint:'Ein Nullniveau für h muss festgelegt werden.'},
{name:'Impuls',formula:'p = m · v',topic:'Mechanik',meaning:'Bewegungsgröße eines Körpers.',units:'kg · m/s',hint:'Impuls ist eine Vektorgröße.'},
{name:'Arbeit',formula:'W = ∫ F · ds',topic:'Mechanik',meaning:'Arbeit als Linienintegral der Kraft entlang des Weges.',units:'J',hint:'Bei konstanter paralleler Kraft gilt W = F · s.'},
{name:'Ohmsches Gesetz',formula:'U = R · I',topic:'Elektrizität',meaning:'Spannung, Widerstand und Stromstärke.',units:'V = Ω · A',hint:'Gilt für ohmsche Bauteile im linearen Bereich.'},
{name:'Coulomb-Kraft',formula:'F = (1 / 4πε₀) · q₁q₂ / r²',topic:'Elektrizität',meaning:'Elektrostatische Kraft zwischen Punktladungen.',units:'N',hint:'Vorzeichen der Ladungen bestimmt Anziehung oder Abstoßung.'},
{name:'Wellenbeziehung',formula:'v = λ · f',topic:'Wellen',meaning:'Ausbreitungsgeschwindigkeit einer Welle.',units:'m/s',hint:'In einem Medium hängt v von dessen Eigenschaften ab.'},
{name:'Photonenenergie',formula:'E = h · f',topic:'Quantenphysik',meaning:'Energie eines Photons.',units:'J',hint:'Mit c = λf folgt E = hc/λ.'},
{name:'Stefan–Boltzmann',formula:'P = σ A T⁴',topic:'Astrophysik',meaning:'Gesamtleistung eines idealen schwarzen Körpers.',units:'W',hint:'T muss in Kelvin eingesetzt werden.'}
];
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('documents'))d.createObjectStore('documents',{keyPath:'id',autoIncrement:true});if(!d.objectStoreNames.contains('cards'))d.createObjectStore('cards',{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function getAll(store){return new Promise((resolve,reject)=>{const r=db.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function addOne(store,value){return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).add(value);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function deleteOne(store,id){return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function clearStore(store){return new Promise((resolve,reject)=>{const r=db.transaction(store,'readwrite').objectStore(store).clear();r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function refresh(){documents=(await getAll('documents')).sort((a,b)=>b.importedAt-a.importedAt);cards=(await getAll('cards')).sort((a,b)=>b.createdAt-a.createdAt);renderAll()}
function showNotice(text){const n=$('#notice');n.textContent=text;n.classList.remove('hidden');clearTimeout(showNotice.t);showNotice.t=setTimeout(()=>n.classList.add('hidden'),4500)}
function go(tab){$$('.tab').forEach(e=>e.classList.remove('active'));$(`#tab-${tab}`).classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#pageTitle').textContent=titles[tab];if(tab==='lab')renderLab()}
$$('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function humanSize(bytes){return bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`}
function classify(file,text=''){const h=`${file.name} ${text.slice(0,2000)}`.toLowerCase();if(/goodnotes|notebook|mitschrift/.test(h))return'Goodnotes';if(/praktikum|versuch|messwert|protokoll|labor/.test(h))return'Praktikum';if(/übung|uebung|exercise|blatt|aufgabe/.test(h))return'Übung';if(/vorlesung|lecture|skript|folien/.test(h))return'Vorlesung';if(/\.csv$|\.tsv$|messdaten|dataset/.test(h))return'Daten';return'Sonstiges'}
async function extractText(file){const ext=file.name.split('.').pop()?.toLowerCase();if(file.type.startsWith('text/')||['txt','md','csv','tsv'].includes(ext))return await file.text();return''}
async function importFiles(files){if(!files.length)return;showNotice('Dateien werden lokal verarbeitet …');for(const file of files){const text=await extractText(file);await addOne('documents',{name:file.name,mime:file.type||'application/octet-stream',size:file.size,kind:classify(file,text),importedAt:Date.now(),text:text.slice(0,2000000),blob:file})}await refresh();showNotice(`${files.length} Datei(en) lokal importiert.`)}
const drop=$('#dropzone'),input=$('#fileInput');$('#chooseFiles').onclick=e=>{e.stopPropagation();input.click()};drop.onclick=()=>input.click();input.onchange=()=>importFiles([...input.files]);drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');importFiles([...e.dataTransfer.files])};
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function openDocument(doc){const u=URL.createObjectURL(doc.blob),a=document.createElement('a');a.href=u;a.target='_blank';a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000)}
function renderFiles(){$('#fileCount').textContent=`${documents.length} Elemente`;$('#fileTable').innerHTML=documents.length?documents.map(d=>`<div class="file-row"><div class="file-icon">▤</div><div class="file-main"><b>${esc(d.name)}</b><small>${humanSize(d.size)} · ${new Date(d.importedAt).toLocaleString('de-DE')}</small></div><span class="tag">${esc(d.kind)}</span><button class="icon-btn open-doc" data-id="${d.id}" title="Öffnen">↗</button><button class="icon-btn delete-doc" data-id="${d.id}" title="Löschen">×</button></div>`).join(''):'<div class="empty">Noch leer.</div>';$$('.delete-doc').forEach(b=>b.onclick=async()=>{await deleteOne('documents',Number(b.dataset.id));await refresh()});$$('.open-doc').forEach(b=>b.onclick=()=>openDocument(documents.find(d=>d.id===Number(b.dataset.id))))}
function renderDashboard(){const good=documents.filter(d=>d.kind==='Goodnotes').length,lab=documents.filter(d=>['Praktikum','Daten'].includes(d.kind)).length;$('#statFiles').textContent=documents.length;$('#statGoodnotes').textContent=good;$('#statLab').textContent=lab;$('#statCards').textContent=cards.length;$('#recentList').innerHTML=documents.length?documents.slice(0,5).map(d=>`<div><i class="file-dot"></i><div><b>${esc(d.name)}</b><small>${esc(d.kind)} · ${humanSize(d.size)}</small></div></div>`).join(''):'<div class="empty">Noch keine Dateien. Dein erster Import landet hier.</div>'}
function renderFormulas(q=''){const x=q.toLowerCase();$('#formulaGrid').innerHTML=formulas.filter(f=>`${f.name} ${f.topic} ${f.meaning}`.toLowerCase().includes(x)).map(f=>`<article class="panel formula-card"><span class="tag">${f.topic}</span><h3>${f.name}</h3><div class="formula">${f.formula}</div><p>${f.meaning}</p><dl><div><dt>Einheit</dt><dd>${f.units}</dd></div><div><dt>Achtung</dt><dd>${f.hint}</dd></div></dl></article>`).join('')}
$('#formulaSearch').oninput=e=>renderFormulas(e.target.value);
function parseDelimited(text,delimiter){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return null;delimiter=delimiter||(lines[0].includes('\t')?'\t':lines[0].includes(';')?';':',');const rows=lines.map(l=>l.split(delimiter).map(v=>v.trim().replace(/^"|"$/g,'')));const numeric=row=>row.every(v=>Number.isFinite(Number(v.replace(',','.'))));const firstNum=numeric(rows[0]),headers=firstNum?rows[0].map((_,i)=>`Spalte ${i+1}`):rows[0],data=firstNum?rows:rows.slice(1),columns=headers.map((_,i)=>data.map(r=>Number((r[i]??'').replace(',','.'))).filter(Number.isFinite));return{headers,columns}}
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN;function sd(a){if(a.length<2)return NaN;const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1))}function regression(x,y){const n=Math.min(x.length,y.length);if(n<2)return null;x=x.slice(0,n);y=y.slice(0,n);const mx=mean(x),my=mean(y),sxx=x.reduce((s,v)=>s+(v-mx)**2,0);if(!sxx)return null;const slope=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0)/sxx,intercept=my-slope*mx,p=x.map(v=>slope*v+intercept),ssr=y.reduce((s,v,i)=>s+(v-p[i])**2,0),sst=y.reduce((s,v)=>s+(v-my)**2,0);return{slope,intercept,r2:sst?1-ssr/sst:1}}
function renderLab(){const data=documents.filter(d=>/\.csv$|\.tsv$/i.test(d.name));const sel=$('#labSelect');sel.innerHTML=data.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('');sel.classList.toggle('hidden',!data.length);$('#labEmpty').classList.toggle('hidden',!!data.length);if(!data.length){$('#labResults').innerHTML='';return}if(!data.some(d=>d.id===Number(sel.value)))sel.value=data[0].id;const d=data.find(x=>x.id===Number(sel.value))||data[0],table=parseDelimited(d.text||'',d.name.toLowerCase().endsWith('.tsv')?'\t':undefined);if(!table){$('#labResults').innerHTML='<article class="panel padded">Keine numerischen Daten erkannt.</article>';return}const summaries=table.headers.map((h,i)=>({h,n:table.columns[i].length,m:mean(table.columns[i]),s:sd(table.columns[i])}));const fit=table.columns.length>=2?regression(table.columns[0],table.columns[1]):null;$('#labResults').innerHTML=`<div class="lab-summary">${summaries.slice(0,4).map(s=>`<article class="panel stat"><span>Σ</span><div><strong>${Number.isFinite(s.m)?s.m.toPrecision(5):'—'}</strong><small>${esc(s.h)} · n=${s.n} · σ=${Number.isFinite(s.s)?s.s.toPrecision(3):'—'}</small></div></article>`).join('')}</div>${fit?`<article class="panel fit-card"><span class="eyebrow">LINEARE REGRESSION · SPALTE 1 → 2</span><div class="fit-equation">y = ${fit.slope.toPrecision(6)} x ${fit.intercept>=0?'+':'−'} ${Math.abs(fit.intercept).toPrecision(6)}</div><div class="fit-meta"><span>R² = <b>${fit.r2.toFixed(6)}</b></span><span>m = <b>${fit.slope.toPrecision(6)}</b></span><span>b = <b>${fit.intercept.toPrecision(6)}</b></span></div></article>`:''}`}
$('#labSelect').onchange=renderLab;
async function addCard(){const front=$('#cardFront').value.trim(),back=$('#cardBack').value.trim(),topic=$('#cardTopic').value.trim()||'Allgemein';if(!front||!back)return showNotice('Vorder- und Rückseite fehlen.');await addOne('cards',{front,back,topic,createdAt:Date.now()});$('#cardFront').value='';$('#cardBack').value='';await refresh()}
$('#addCard').onclick=addCard;function renderCards(){$('#cardCount').textContent=cards.length;$('#cardList').innerHTML=cards.length?cards.map(c=>`<article><span class="tag">${esc(c.topic)}</span><b>${esc(c.front)}</b><p>${esc(c.back)}</p><button class="text-btn delete-card" data-id="${c.id}">Löschen</button></article>`).join(''):'<div class="empty">Noch keine Lernkarten.</div>';$$('.delete-card').forEach(b=>b.onclick=async()=>{await deleteOne('cards',Number(b.dataset.id));await refresh()})}
$('#exportCards').onclick=()=>{if(!cards.length)return showNotice('Noch keine Lernkarten vorhanden.');const csv=cards.map(c=>`"${c.front.replaceAll('"','""')}","${c.back.replaceAll('"','""')}"`).join('\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),'physics-os-goodnotes-cards.csv')};
function bytesToB64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}function b64ToBytes(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}async function deriveKey(pass,salt){const m=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function makePayload(){const docs=await Promise.all(documents.map(async d=>({name:d.name,mime:d.mime,size:d.size,kind:d.kind,importedAt:d.importedAt,text:d.text,data:bytesToB64(new Uint8Array(await d.blob.arrayBuffer()))})));return{version:1,updatedAt:new Date().toISOString(),deviceId:getDeviceId(),documents:docs,cards:cards.map(({front,back,topic,createdAt})=>({front,back,topic,createdAt}))}}
async function encryptPayload(payload,pass){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(pass,salt),encrypted=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(payload))));return{v:1,salt:bytesToB64(salt),iv:bytesToB64(iv),data:bytesToB64(encrypted)}}
async function decryptEnvelope(env,pass){const salt=b64ToBytes(env.salt),iv=b64ToBytes(env.iv),key=await deriveKey(pass,salt),dec=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,b64ToBytes(env.data));return JSON.parse(new TextDecoder().decode(dec))}
async function replaceWithPayload(payload){if(payload.version!==1)throw new Error('VERSION');await clearStore('documents');await clearStore('cards');for(const d of payload.documents||[]){await addOne('documents',{...d,blob:new Blob([b64ToBytes(d.data)],{type:d.mime}),data:undefined})}for(const c of payload.cards||[])await addOne('cards',c);await refresh()}
async function exportVault(){const pass=$('#vaultPass').value;if(pass.length<8)return showNotice('Der Vault-Code sollte mindestens 8 Zeichen haben.');const payload=await makePayload(),env=await encryptPayload(payload,pass);downloadBlob(new Blob([JSON.stringify(env)],{type:'application/json'}),`physics-os-vault-${new Date().toISOString().slice(0,10)}.json`);showNotice('Verschlüsseltes Vault-Backup erstellt.')}
async function importVault(file){try{const pass=$('#vaultPass').value;if(pass.length<8)throw new Error('PASS');const env=JSON.parse(await file.text()),payload=await decryptEnvelope(env,pass);await replaceWithPayload(payload);showNotice('Vault erfolgreich wiederhergestellt.')}catch{showNotice('Vault konnte nicht geöffnet werden. Prüfe Datei und Code.')}}
$('#exportVault').onclick=exportVault;$('#importVaultBtn').onclick=()=>$('#vaultInput').click();$('#vaultInput').onchange=e=>{if(e.target.files[0])importVault(e.target.files[0])};
const syncConfig=loadSyncConfig();
function syncFields(){return{endpoint:$('#syncEndpoint').value.trim(),syncId:$('#syncId').value.trim(),autoSync:$('#autoSync').checked}}
function persistSyncFields(){saveSyncConfig(syncFields());renderSyncState()}
function renderSyncState(){const c=syncFields();const connected=Boolean(c.endpoint&&c.syncId);$('#syncState').textContent=connected?'bereit':'nicht verbunden';$('#syncPill').textContent=connected?'↻ Sync bereit':'✓ lokal-first';$('#lastSync').textContent=localStorage.getItem('physics-os-last-sync')||'noch nie'}
function validateSync(){const c=syncFields(),pass=$('#syncPass').value;if(!c.endpoint)return showNotice('Trage zuerst den Sync-Endpunkt ein.'),null;if(!c.syncId)return showNotice('Erzeuge oder trage eine Sync-ID ein.'),null;if(pass.length<8)return showNotice('Der Vault-Code muss mindestens 8 Zeichen haben.'),null;return{...c,pass}}
async function syncPush(){const c=validateSync();if(!c)return;try{showNotice('Verschlüssele und lade den aktuellen Stand …');const payload=await makePayload(),envelope=await encryptPayload(payload,c.pass);await pushEncryptedSnapshot({endpoint:c.endpoint,syncId:c.syncId,envelope,deviceId:getDeviceId()});localStorage.setItem('physics-os-last-sync',new Date().toLocaleString('de-DE'));renderSyncState();showNotice('Verschlüsselter Stand wurde synchronisiert.')}catch(e){console.error(e);showNotice('Cloud-Sync nicht erreichbar. Prüfe den Endpunkt.')}}
async function syncPull(){const c=validateSync();if(!c)return;try{showNotice('Lade verschlüsselten Cloud-Stand …');const remote=await pullEncryptedSnapshot({endpoint:c.endpoint,syncId:c.syncId});if(!remote)return showNotice('Für diese Sync-ID gibt es noch keinen Cloud-Stand.');const payload=await decryptEnvelope(remote.envelope,c.pass);await replaceWithPayload(payload);localStorage.setItem('physics-os-last-sync',new Date().toLocaleString('de-DE'));renderSyncState();showNotice('Cloud-Stand wurde auf dieses Gerät geladen.')}catch(e){console.error(e);showNotice('Sync konnte nicht gelesen werden. Prüfe Endpunkt, Sync-ID und Vault-Code.')}}
async function syncNow(){const c=validateSync();if(!c)return;try{const remote=await pullEncryptedSnapshot({endpoint:c.endpoint,syncId:c.syncId});if(!remote)return syncPush();const remotePayload=await decryptEnvelope(remote.envelope,c.pass);const localNewest=Math.max(0,...documents.map(d=>d.importedAt||0),...cards.map(x=>x.createdAt||0));const remoteNewest=Math.max(0,...(remotePayload.documents||[]).map(d=>d.importedAt||0),...(remotePayload.cards||[]).map(x=>x.createdAt||0));if(remoteNewest>localNewest){await replaceWithPayload(remotePayload);showNotice('Der neuere Cloud-Stand wurde übernommen.')}else{await syncPush();return}localStorage.setItem('physics-os-last-sync',new Date().toLocaleString('de-DE'));renderSyncState()}catch(e){console.error(e);showNotice('Automatischer Sync fehlgeschlagen.')}}
$('#deviceId').value=getDeviceId();$('#syncEndpoint').value=syncConfig.endpoint||'';$('#syncId').value=syncConfig.syncId||'';$('#autoSync').checked=Boolean(syncConfig.autoSync);
['#syncEndpoint','#syncId'].forEach(id=>$(id).addEventListener('change',persistSyncFields));$('#autoSync').addEventListener('change',persistSyncFields);
$('#generateSyncId').onclick=()=>{$('#syncId').value=generateSyncId();persistSyncFields();showNotice('Neue zufällige Sync-ID erzeugt. Speichere sie sicher.')};
$('#copySyncId').onclick=async()=>{const id=$('#syncId').value.trim();if(!id)return showNotice('Noch keine Sync-ID vorhanden.');await navigator.clipboard.writeText(id);showNotice('Sync-ID kopiert.')};
$('#syncPush').onclick=syncPush;$('#syncPull').onclick=syncPull;$('#syncNow').onclick=syncNow;renderSyncState();
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&loadSyncConfig().autoSync&&$('#syncPass').value.length>=8)syncNow()});
function renderAll(){renderDashboard();renderFiles();renderCards();renderLab()}
(async()=>{await openDB();renderFormulas();await refresh();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{})})().catch(e=>{console.error(e);showNotice('Die lokale Datenbank konnte nicht geöffnet werden.')});
