const SEM_KEY='physicsOS.sem1.progress.v1';
const PRACT_KEY='physicsOS.sem1.practicum.v1';

const semesterModules=[
  {
    id:'mechanik', code:'P 1', name:'Experimentalphysik I', short:'Mechanik', ects:9, graded:true, gop:true, accent:'M',
    topics:[['newton','Newtonsche Mechanik'],['schwingungen','Schwingungen & Wellen'],['starr','Starre Körper'],['deformierbar','Deformierbare Körper'],['hydrostatik','Hydrostatik'],['hydrodynamik','Hydrodynamik'],['relativitaet','Spezielle Relativitätstheorie']],
    bridge:[['Newton & Bewegung','Vektoren · Ableitungen · Differentialgleichungen'],['Schwingungen','Differentialgleichungen · komplexe Zahlen'],['Starre Körper','Vektoren · Matrizen · Eigenwerte'],['Strömungen','Vektoranalysis · Integrale']]
  },
  {
    id:'rechenmethoden', code:'P 2', name:'Rechenmethoden', short:'Theoretische Physik', ects:9, graded:false, gop:true, accent:'R',
    topics:[['komplex','Komplexe Zahlen'],['vektor','Vektoranalysis'],['koordinaten','Koordinatentransformationen'],['matrizen','Matrizen & Eigenwertprobleme'],['diff','Differentiation'],['integral','Integration'],['mehrdim','Mehrere Veränderliche'],['distributionen','Distributionen'],['fourier','Fourier-Analysis'],['approx','Approximationsmethoden'],['dgl','Differentialgleichungen'],['gauss-stokes','Gauß & Stokes']],
    bridge:[['Mechanik','Vektoren · DGL · Integrale'],['Schwingungen','Komplexe Zahlen · Fourier'],['Felder & Strömungen','Vektoranalysis · Gauß · Stokes']]
  },
  {
    id:'linalg', code:'P 3', name:'Mathematik I', short:'Lineare Algebra', ects:9, graded:false, gop:false, accent:'L',
    topics:[['grundbegriffe','Grundbegriffe der linearen Algebra'],['vektorraeume','Vektorräume'],['abbildungen','Lineare Abbildungen'],['matrizen','Matrizen'],['det','Determinanten'],['eigen','Eigenwerte & Eigenvektoren'],['diagonal','Diagonalisierung'],['hauptachsen','Hauptachsentransformation']],
    bridge:[['Koordinatenwechsel','Matrizen · lineare Abbildungen'],['Starre Körper','Eigenwerte · Hauptachsen'],['Gekoppelte Schwingungen','Eigenwerte · Diagonalisierung']]
  },
  {
    id:'praktikum', code:'P 4.1', name:'Grundpraktikum I', short:'Experiment & Protokoll', ects:3, graded:false, gop:false, accent:'P',
    topics:[['messung','Messgrößen & Einheiten'],['unsicherheit','Messunsicherheiten'],['auswertung','Daten auswerten'],['plots','Diagramme & Fits'],['diskussion','Ergebnisse kritisch bewerten'],['protokoll','Wissenschaftlich dokumentieren']],
    bridge:[['Versuch','Modell ↔ Messung'],['Auswertung','Unsicherheit · Fit · Einheiten'],['Protokoll','Nachvollziehbarkeit · kritische Diskussion']]
  }
];

const statusMeta=[{label:'neu',symbol:'○'},{label:'üben',symbol:'◐'},{label:'sicher',symbol:'●'}];
function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch{return fallback}}
function saveJSON(key,value){localStorage.setItem(key,JSON.stringify(value))}
function progressState(){return readJSON(SEM_KEY,{})}
function topicStatus(moduleId,topicId){return Number(progressState()?.[moduleId]?.[topicId]||0)}
function setTopicStatus(moduleId,topicId,status){const state=progressState();state[moduleId] ||= {};state[moduleId][topicId]=status;saveJSON(SEM_KEY,state)}
function moduleProgress(module){const values=module.topics.map(([id])=>topicStatus(module.id,id));return values.length?Math.round(values.reduce((a,b)=>a+b,0)/(values.length*2)*100):0}
function overallProgress(){const topics=semesterModules.flatMap(m=>m.topics.map(([id])=>topicStatus(m.id,id)));return topics.length?Math.round(topics.reduce((a,b)=>a+b,0)/(topics.length*2)*100):0}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

function semesterMarkup(){return `
<section class="sem1-shell" id="semesterOne">
  <div class="sem1-topline"><div><span class="sem1-kicker">LMU · 1. SEMESTER</span><h2>Dein Semester auf einen Blick</h2></div><div class="sem1-overall"><strong id="sem1Overall">0%</strong><span>Themenfortschritt</span></div></div>
  <div class="sem1-focus panel"><div><span class="sem1-label">Nächster sinnvoller Fokus</span><strong id="sem1FocusTitle">—</strong><small id="sem1FocusMeta"></small></div><button class="secondary" id="sem1OpenFocus">Öffnen</button></div>
  <div class="sem1-grid" id="sem1ModuleGrid"></div>
  <div class="sem1-strip panel"><div><span class="sem1-label">GOP</span><strong>Mechanik · Rechenmethoden</strong></div><div id="sem1GopState" class="sem1-gop-state"></div><button class="sem1-info" data-sem1-info="Die GOP besteht im 1. Fachsemester aus Experimentalphysik I: Mechanik und Rechenmethoden der theoretischen Physik. Diese Anzeige ist nur dein Lernfortschritt, kein offizieller Prüfungsstatus.">i</button></div>
  <details class="sem1-tools panel"><summary><span><b>Lernwerkstatt</b><small>Rechenmethoden · Lineare Algebra · Praktikum</small></span><span>⌄</span></summary><div class="sem1-tool-tabs" id="sem1ToolTabs"><button data-tool="complex" class="active">Komplexe Zahlen</button><button data-tool="vectors">Vektoren</button><button data-tool="matrix">Matrizen</button><button data-tool="practicum">Protokoll-Check</button></div><div id="sem1ToolBody" class="sem1-tool-body"></div></details>
</section>`}

function moduleCard(m){const p=moduleProgress(m);return `<button class="sem1-module-card panel" data-sem1-module="${m.id}"><div class="sem1-module-head"><span class="sem1-module-mark">${m.accent}</span><span>${m.gop?'<b class="sem1-gop">GOP</b>':''}</span></div><div><small>${m.code} · ${m.ects} ECTS</small><h3>${m.name}</h3><span>${m.short}</span></div><div class="sem1-progress"><i style="width:${p}%"></i></div><div class="sem1-module-foot"><span>${p}%</span><span>${m.graded?'benotet':'unbenotet'} · öffnen →</span></div></button>`}
function renderSemester(){const grid=document.querySelector('#sem1ModuleGrid');if(!grid)return;grid.innerHTML=semesterModules.map(moduleCard).join('');document.querySelector('#sem1Overall').textContent=`${overallProgress()}%`;renderGop();renderFocus();grid.querySelectorAll('[data-sem1-module]').forEach(btn=>btn.addEventListener('click',()=>openModule(btn.dataset.sem1Module)))}
function renderGop(){const box=document.querySelector('#sem1GopState');if(!box)return;box.innerHTML=semesterModules.filter(m=>m.gop).map(m=>`<span>${m.id==='mechanik'?'Mechanik':'Rechenmethoden'} <b>${moduleProgress(m)}%</b></span>`).join('')}
function nextFocus(){const ordered=[...semesterModules].sort((a,b)=>{if(a.gop!==b.gop)return a.gop?-1:1;return moduleProgress(a)-moduleProgress(b)});for(const m of ordered){const topic=m.topics.find(([id])=>topicStatus(m.id,id)<2);if(topic)return {module:m,topic}}return {module:semesterModules[0],topic:semesterModules[0].topics[0]}}
function renderFocus(){const f=nextFocus(),title=document.querySelector('#sem1FocusTitle'),meta=document.querySelector('#sem1FocusMeta'),btn=document.querySelector('#sem1OpenFocus');if(!title)return;title.textContent=f.topic[1];meta.textContent=`${f.module.name}${f.module.gop?' · GOP':''}`;btn.dataset.module=f.module.id;btn.onclick=()=>openModule(btn.dataset.module)}

function ensureModal(){if(document.querySelector('#sem1Modal'))return;document.body.insertAdjacentHTML('beforeend','<div id="sem1Modal" class="sem1-modal hidden"><div class="sem1-modal-card"><button class="sem1-close" aria-label="Schließen">×</button><div id="sem1ModalBody"></div></div></div>');const modal=document.querySelector('#sem1Modal');modal.querySelector('.sem1-close').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')}}
function openModule(id){ensureModal();const m=semesterModules.find(x=>x.id===id);if(!m)return;const body=document.querySelector('#sem1ModalBody');body.innerHTML=`<div class="sem1-modal-title"><div><span class="sem1-kicker">${m.code} · ${m.ects} ECTS ${m.gop?'· GOP':''}</span><h2>${m.name}</h2><p>${m.short}</p></div><strong>${moduleProgress(m)}%</strong></div><div class="sem1-modal-grid"><section><div class="sem1-section-title"><h3>Themen</h3><span>anklicken: neu → üben → sicher</span></div><div class="sem1-topic-list">${m.topics.map(([tid,label])=>topicRow(m,tid,label)).join('')}</div></section><aside><div class="sem1-side-card"><h3>Mathe ↔ Physik</h3>${m.bridge.map(([a,b])=>`<div><b>${a}</b><span>${b}</span></div>`).join('')}</div>${m.id==='mechanik'?'<button class="secondary full" id="sem1MechanicsFormulas">Mechanik-Formeln öffnen</button>':''}${['rechenmethoden','linalg'].includes(m.id)?'<button class="secondary full" id="sem1OpenTools">Lernwerkstatt öffnen</button>':''}${m.id==='praktikum'?'<button class="secondary full" id="sem1OpenProtocol">Protokoll-Check öffnen</button>':''}</aside></div>`;document.querySelector('#sem1Modal').classList.remove('hidden');body.querySelectorAll('[data-sem1-topic]').forEach(btn=>btn.onclick=()=>cycleTopic(m,btn.dataset.sem1Topic));body.querySelector('#sem1MechanicsFormulas')?.addEventListener('click',openMechanicsFormulas);body.querySelector('#sem1OpenTools')?.addEventListener('click',()=>{document.querySelector('#sem1Modal').classList.add('hidden');openTools(m.id==='linalg'?'matrix':'complex')});body.querySelector('#sem1OpenProtocol')?.addEventListener('click',()=>{document.querySelector('#sem1Modal').classList.add('hidden');openTools('practicum')})}
function topicRow(m,tid,label){const s=topicStatus(m.id,tid),meta=statusMeta[s];return `<button class="sem1-topic status-${s}" data-sem1-topic="${tid}"><span class="sem1-status-dot">${meta.symbol}</span><span>${label}</span><small>${meta.label}</small></button>`}
function cycleTopic(m,tid){setTopicStatus(m.id,tid,(topicStatus(m.id,tid)+1)%3);renderSemester();openModule(m.id);updateDashboardStat()}
function openMechanicsFormulas(){document.querySelector('#sem1Modal')?.classList.add('hidden');document.querySelector('#nav [data-tab="formulas"]')?.click();setTimeout(()=>{const select=document.querySelector('#formulaTopic');if(select){select.value='Mechanik';select.dispatchEvent(new Event('change',{bubbles:true}))}},60)}

let tool='complex';
function openTools(which){const details=document.querySelector('.sem1-tools');if(!details)return;details.open=true;details.scrollIntoView({behavior:'smooth',block:'start'});setTool(which)}
function setTool(which){tool=which;document.querySelectorAll('#sem1ToolTabs [data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===which));renderTool()}
function renderTool(){const body=document.querySelector('#sem1ToolBody');if(!body)return;if(tool==='complex')renderComplex(body);if(tool==='vectors')renderVectors(body);if(tool==='matrix')renderMatrix(body);if(tool==='practicum')renderPracticum(body)}
function rnd(min,max){return Math.floor(Math.random()*(max-min+1))+min}
let complexTask=null;
function newComplex(){const op=Math.random()<.5?'+':'×',a=rnd(-6,8),b=rnd(-6,8),c=rnd(-6,8),d=rnd(-6,8);let re,im;if(op==='+'){re=a+c;im=b+d}else{re=a*c-b*d;im=a*d+b*c}complexTask={a,b,c,d,op,re,im}}
function cfmt(a,b){return `${a}${b<0?' − ':' + '}${Math.abs(b)}i`}
function renderComplex(body){if(!complexTask)newComplex();body.innerHTML=`<div class="sem1-practice"><div class="sem1-practice-head"><div><span class="sem1-label">RECHENMETHODEN</span><h3>Komplexe Zahlen</h3></div><button class="sem1-info" data-sem1-info="Kein Timer. Rechne Real- und Imaginärteil getrennt. Bei der Multiplikation gilt i² = −1.">i</button></div><div class="sem1-big-task">(${cfmt(complexTask.a,complexTask.b)}) ${complexTask.op} (${cfmt(complexTask.c,complexTask.d)})</div><div class="sem1-answer-row"><input id="complexRe" inputmode="numeric" placeholder="Realteil"><span>+</span><input id="complexIm" inputmode="numeric" placeholder="Imaginärteil"><span>i</span></div><div class="button-row"><button class="primary" id="complexCheck">Prüfen</button><button class="secondary" id="complexNew">Neue Aufgabe</button><button class="text-btn" id="complexTip">Tipp</button></div><div id="complexFeedback" class="sem1-feedback"></div></div>`;hookInfo(body);body.querySelector('#complexCheck').onclick=()=>{const re=Number(body.querySelector('#complexRe').value),im=Number(body.querySelector('#complexIm').value);body.querySelector('#complexFeedback').innerHTML=(re===complexTask.re&&im===complexTask.im)?'<b>✓ richtig</b>':`Noch nicht. <span>Ergebnis: ${cfmt(complexTask.re,complexTask.im)}</span>`};body.querySelector('#complexNew').onclick=()=>{newComplex();renderComplex(body)};body.querySelector('#complexTip').onclick=()=>{body.querySelector('#complexFeedback').innerHTML=complexTask.op==='+'?'Addiere Realteile miteinander und Imaginärteile miteinander.':'Ausmultiplizieren und i² durch −1 ersetzen: (a+bi)(c+di)=(ac−bd)+(ad+bc)i.'}}
let vectorTask=null;
function newVector(){const u=[rnd(-6,8),rnd(-6,8),rnd(-6,8)],v=[rnd(-6,8),rnd(-6,8),rnd(-6,8)];vectorTask={u,v,dot:u.reduce((s,x,i)=>s+x*v[i],0)}}
function renderVectors(body){if(!vectorTask)newVector();const {u,v}=vectorTask;body.innerHTML=`<div class="sem1-practice"><div class="sem1-practice-head"><div><span class="sem1-label">RECHENMETHODEN</span><h3>Vektoren</h3></div><button class="sem1-info" data-sem1-info="Das Skalarprodukt zweier Vektoren ist u·v = u₁v₁ + u₂v₂ + u₃v₃. Es liefert eine Zahl, keinen Vektor.">i</button></div><div class="sem1-big-task">u = (${u.join(', ')}) &nbsp; · &nbsp; v = (${v.join(', ')})</div><div class="sem1-question-note">Berechne das Skalarprodukt u · v.</div><div class="sem1-answer-row single"><input id="vectorAnswer" inputmode="numeric" placeholder="Ergebnis"></div><div class="button-row"><button class="primary" id="vectorCheck">Prüfen</button><button class="secondary" id="vectorNew">Neue Aufgabe</button><button class="text-btn" id="vectorTip">Rechenweg</button></div><div id="vectorFeedback" class="sem1-feedback"></div></div>`;hookInfo(body);body.querySelector('#vectorCheck').onclick=()=>{const a=Number(body.querySelector('#vectorAnswer').value);body.querySelector('#vectorFeedback').innerHTML=a===vectorTask.dot?'<b>✓ richtig</b>':`Noch nicht. Das Ergebnis ist <b>${vectorTask.dot}</b>.`};body.querySelector('#vectorNew').onclick=()=>{newVector();renderVectors(body)};body.querySelector('#vectorTip').onclick=()=>{body.querySelector('#vectorFeedback').innerHTML=`${u[0]}·${v[0]} + ${u[1]}·${v[1]} + ${u[2]}·${v[2]} = <b>${vectorTask.dot}</b>`}}
function fmt(n){return Number.isInteger(n)?String(n):Number(n.toFixed(3)).toLocaleString('de-DE')}
function renderMatrix(body){body.innerHTML=`<div class="sem1-practice"><div class="sem1-practice-head"><div><span class="sem1-label">LINEARE ALGEBRA</span><h3>2×2-Matrix</h3></div><button class="sem1-info" data-sem1-info="Für A=[[a,b],[c,d]] gilt det(A)=ad−bc. Eine Determinante von 0 bedeutet: Die Matrix ist nicht invertierbar.">i</button></div><div class="matrix-workbench"><div class="matrix-bracket"><input id="ma" value="2"><input id="mb" value="1"><input id="mc" value="-1"><input id="md" value="3"></div><div class="matrix-actions"><button class="primary" id="matrixCalc">Auswerten</button><button class="secondary" id="matrixRandom">Zufällige Matrix</button></div></div><div id="matrixResult" class="matrix-result"></div></div>`;hookInfo(body);const calc=()=>{const vals=['ma','mb','mc','md'].map(id=>Number(body.querySelector('#'+id).value));if(vals.some(v=>!Number.isFinite(v)))return;const [a,b,c,d]=vals,det=a*d-b*c,tr=a+d,disc=tr*tr-4*det;let eigen='komplexe Eigenwerte';if(disc>=0){const root=Math.sqrt(disc);eigen=`λ₁ = ${fmt((tr+root)/2)}, λ₂ = ${fmt((tr-root)/2)}`}body.querySelector('#matrixResult').innerHTML=`<div><span>Determinante</span><b>${fmt(det)}</b><small>${a}·${d} − ${b}·${c}</small></div><div><span>Spur</span><b>${fmt(tr)}</b><small>a + d</small></div><div><span>Eigenwerte</span><b>${eigen}</b><small>aus λ² − tr(A)λ + det(A)=0</small></div>`};body.querySelector('#matrixCalc').onclick=calc;body.querySelector('#matrixRandom').onclick=()=>{['ma','mb','mc','md'].forEach(id=>body.querySelector('#'+id).value=rnd(-5,6));calc()};calc()}
const protocolItems=['Fragestellung/Ziel klar formuliert','Messgrößen mit Einheiten angegeben','Unsicherheiten berücksichtigt','Achsen im Diagramm beschriftet','Fit/Modell sinnvoll begründet','Ergebnis mit Einheit & Unsicherheit','Abweichungen kritisch diskutiert','Versuch nachvollziehbar dokumentiert'];
function renderPracticum(body){const state=readJSON(PRACT_KEY,{});body.innerHTML=`<div class="sem1-practice"><div class="sem1-practice-head"><div><span class="sem1-label">GRUNDPRAKTIKUM</span><h3>Protokoll-Check</h3></div><button class="sem1-info" data-sem1-info="Die Liste orientiert sich an den Lernzielen des Grundpraktikums: wissenschaftliches Dokumentieren, Auswerten und kritisches Bewerten. Sie ersetzt keine versuchsspezifischen Vorgaben.">i</button></div><div class="protocol-list">${protocolItems.map((x,i)=>`<label><input type="checkbox" data-proto="${i}" ${state[i]?'checked':''}><span>${x}</span></label>`).join('')}</div><button class="text-btn" id="protocolReset">Liste zurücksetzen</button></div>`;hookInfo(body);body.querySelectorAll('[data-proto]').forEach(ch=>ch.onchange=()=>{const s=readJSON(PRACT_KEY,{});s[ch.dataset.proto]=ch.checked;saveJSON(PRACT_KEY,s)});body.querySelector('#protocolReset').onclick=()=>{localStorage.removeItem(PRACT_KEY);renderPracticum(body)}}
function hookInfo(scope=document){scope.querySelectorAll('.sem1-info').forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.onclick=e=>{e.stopPropagation();let tip=document.querySelector('#sem1InfoTip');if(!tip){document.body.insertAdjacentHTML('beforeend','<div id="sem1InfoTip" class="sem1-info-tip hidden"></div>');tip=document.querySelector('#sem1InfoTip')}tip.textContent=btn.dataset.sem1Info||'';tip.classList.remove('hidden');const r=btn.getBoundingClientRect(),w=Math.min(340,innerWidth-24);tip.style.width=w+'px';tip.style.left=Math.max(12,Math.min(innerWidth-w-12,r.right-w))+'px';tip.style.top=Math.min(innerHeight-150,r.bottom+8)+'px'}})}
function addFormulaSemesterChip(){const toolbar=document.querySelector('#tab-formulas .toolbar');if(!toolbar||document.querySelector('#sem1FormulaChip'))return;const btn=document.createElement('button');btn.id='sem1FormulaChip';btn.className='chip';btn.textContent='1. Semester · Mechanik';btn.title='Nur Mechanik-Formeln anzeigen';btn.onclick=()=>{const sel=document.querySelector('#formulaTopic');if(sel){sel.value='Mechanik';sel.dispatchEvent(new Event('change',{bubbles:true}));btn.classList.add('active')}};toolbar.appendChild(btn);document.querySelector('#formulaTopic')?.addEventListener('change',()=>btn.classList.toggle('active',document.querySelector('#formulaTopic').value==='Mechanik'))}
function addDashboardSemester(){const home=document.querySelector('#tab-home .stats-grid');if(!home||document.querySelector('#sem1DashStat'))return;const card=document.createElement('article');card.className='panel stat';card.id='sem1DashStat';card.innerHTML=`<strong>${overallProgress()}%</strong><span>1. Semester</span>`;card.onclick=()=>document.querySelector('#nav [data-tab="study"]')?.click();home.appendChild(card)}
function updateDashboardStat(){const s=document.querySelector('#sem1DashStat strong');if(s)s.textContent=`${overallProgress()}%`}
function init(){const study=document.querySelector('#tab-study');if(!study)return;const head=study.querySelector('.section-head');if(head?.querySelector('h2'))head.querySelector('h2').textContent='Studium · 1. Semester';if(!document.querySelector('#semesterOne'))head?.insertAdjacentHTML('afterend',semesterMarkup());renderSemester();document.querySelectorAll('#sem1ToolTabs [data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));renderTool();hookInfo();document.addEventListener('click',e=>{if(!e.target.closest('.sem1-info')&&!e.target.closest('#sem1InfoTip'))document.querySelector('#sem1InfoTip')?.classList.add('hidden')});addFormulaSemesterChip();addDashboardSemester();const navStudy=document.querySelector('#nav [data-tab="study"] em');if(navStudy)navStudy.textContent='1. Semester'}
if(document.readyState==='complete')init();else window.addEventListener('load',()=>setTimeout(init,0),{once:true});